import { describe, expect, test } from 'bun:test'
import { rootShim, siblingShim } from '../src/linker/shim.ts'
import { parseTypeExports } from '../src/linker/type-exports.ts'

/**
 * What a shim forwards, and what it refuses to.
 *
 * The refusals matter more than the successes. A type that is missed costs the user
 * the annotation they were going to write by hand; a type that is forwarded wrongly
 * puts an error in a generated file they did not write and cannot fix.
 */

const names = (source: string) => parseTypeExports(source).map((type) => type.name)

describe('reading a module', () => {
  test('finds a plain alias', () => {
    expect(names('export type Node = string\nreturn {}')).toEqual(['Node'])
  })

  test('keeps generic parameters, and drops their defaults on the right', () => {
    const [type] = parseTypeExports('export type PureComponent<Props, State = nil> = Impl.P')
    expect(type).toEqual({
      name: 'PureComponent',
      declared: 'Props, State = nil',
      applied: 'Props, State',
    })
  })

  test('handles a generic pack', () => {
    const [type] = parseTypeExports('export type Fn<A..., R...> = (A...) -> R...')
    expect(type?.applied).toBe('A..., R...')
  })

  // `<T, U = Map<string, T>>` is two parameters and every naive split makes it four.
  test('a default containing commas is still one parameter', () => {
    const [type] = parseTypeExports('export type Store<T, U = { [string]: T }> = Impl.S')
    expect(type?.applied).toBe('T, U')
  })

  test('a type alias that is not exported stays private', () => {
    expect(names('type Internal = string\nexport type Public = number')).toEqual(['Public'])
  })

  // The reason the source is stripped first: packages document themselves in Luau.
  test('a doc comment is not a declaration', () => {
    const source = ['--[=[', '  export type Imaginary = string', ']=]', 'export type Real = number']
    expect(names(source.join('\n'))).toEqual(['Real'])
  })

  test('a type function is not an alias', () => {
    expect(names('export type function rawget(t) return t end')).toEqual([])
  })

  test('a module with no types produces none', () => {
    expect(names('local M = {}\nreturn M')).toEqual([])
  })
})

describe('what is refused', () => {
  /**
   * A default may name any type the module also exports, because the shim re-exports
   * that one too. It may not name a type the module keeps to itself: that compiles in
   * the package and not in the shim.
   */
  test('a default naming another exported type is fine', () => {
    expect(names('export type Object = any\nexport type Element<P = Object> = Impl.E')).toEqual([
      'Object',
      'Element',
    ])
  })

  test('a default naming a private type takes the whole declaration out', () => {
    expect(names('type Secret = string\nexport type Element<P = Secret> = Impl.E')).toEqual([])
  })

  test('a default naming a builtin is fine', () => {
    expect(names('export type Element<P = string, Q = nil> = Impl.E')).toEqual(['Element'])
  })

  test('a default naming an earlier parameter is fine', () => {
    expect(names('export type Pair<A, B = A> = Impl.P')).toEqual(['Pair'])
  })

  /**
   * Dropping one can strand another, so the filter runs to a fixed point: a default
   * naming a type that was itself dropped is no better off than one naming a type
   * that was never exported at all.
   */
  test('a default naming a dropped type is dropped too', () => {
    const source = [
      'type Secret = string',
      'export type First<P = Secret> = Impl.F',
      'export type Second<Q = First> = Impl.S',
    ]
    expect(names(source.join('\n'))).toEqual([])
  })

  test('an unterminated parameter list is skipped, not guessed at', () => {
    expect(names('export type Broken<T = ')).toEqual([])
  })
})

describe('the shim it produces', () => {
  test('a package with no types keeps the one-line shim', () => {
    expect(rootShim('evaera_promise@4.0.0', 'promise')).toBe(
      '-- Generated by Rarn. Do not edit; reinstalling overwrites this file.\n' +
        'return require(script.Parent._Index["evaera_promise@4.0.0"]["promise"])\n',
    )
  })

  test('a package with types binds the module and forwards them', () => {
    const types = parseTypeExports('export type Node = any\nexport type Binding<T> = Impl.B')
    const shim = siblingShim('jsdotlua_react@17.2.1', 'react', types)

    expect(shim).toContain('local Module = require(script.Parent.Parent["jsdotlua_react@17.2.1"]')
    expect(shim).toContain('export type Node = Module.Node')
    expect(shim).toContain('export type Binding<T> = Module.Binding<T>')
    expect(shim.trimEnd().endsWith('return Module')).toBe(true)
  })

  /**
   * `export type Module` is an ordinary thing to declare, and a type alias sharing the
   * binding's name would make every forwarded line refer to itself.
   */
  test('the binding avoids a type of the same name', () => {
    const shim = rootShim('a_b@1.0.0', 'b', parseTypeExports('export type Module = any'))
    expect(shim).toContain('local RarnModule = require(')
    expect(shim).toContain('export type Module = RarnModule.Module')
  })

  // Installing checks for this before replacing a directory, so an existing install
  // has to stay recognisable across the change of shape.
  test('the marker is still on the first line', () => {
    const shim = rootShim('a_b@1.0.0', 'b', parseTypeExports('export type X = any'))
    expect(shim.split('\n')[0]).toContain('Generated by Rarn')
  })
})

describe('an arrow is not a closing bracket', () => {
  /**
   * `developmentfurthered/signal` declares this, and it is ordinary Luau: a function
   * type as a generic default. Counting the `>` of `->` as the end of the parameter
   * list cut the declaration in half, and the shim came out as
   * `export type NamedEvent<Listener = (...any) -> = Module.NamedEvent<Listener>` —
   * which is not Luau at all.
   *
   * Found by generating shims for every package in a warm cache and running
   * `luau-lsp analyze` over all 578 of them, which is the only thing that could have:
   * two packages out of 318 with types, and the failure is a SyntaxError in a file the
   * user never wrote.
   */
  const REAL = 'export type NamedEvent<Listener = (...any) -> (), A... = ...any> = {}'

  test('a function type in a default does not end the parameter list', () => {
    const [type] = parseTypeExports(REAL)
    expect(type?.declared).toBe('Listener = (...any) -> (), A... = ...any')
    expect(type?.applied).toBe('Listener, A...')
  })

  test('the shim it produces is the whole declaration', () => {
    const shim = rootShim('a_b@1.0.0', 'b', parseTypeExports(REAL))
    expect(shim).toContain(
      'export type NamedEvent<Listener = (...any) -> (), A... = ...any> = Module.NamedEvent<Listener, A...>',
    )
  })

  // The referenced types are exported here on purpose: a default naming something the
  // module keeps private is dropped, and a test that let that happen would pass while
  // measuring the wrong rule.
  test('a real closing bracket still closes', () => {
    const source = [
      'export type Map<K, V> = {}',
      'export type Store<T = Map<string, number>, U = nil> = {}',
    ]
    expect(parseTypeExports(source.join('\n')).at(-1)?.applied).toBe('T, U')
  })

  test('an arrow returning a generic is not confused either', () => {
    const source = [
      'export type Array<T> = {}',
      'export type Fn<T = () -> Array<string>, U = nil> = {}',
    ]
    expect(parseTypeExports(source.join('\n')).at(-1)?.applied).toBe('T, U')
  })

  test('a default naming a private type is still dropped, brackets or not', () => {
    expect(names('type Secret = {}\nexport type Fn<T = () -> Secret> = {}')).toEqual([])
  })
})
