import type { PlaceInfo } from '../manifest/types.ts'
import type { Placement } from '../resolver/types.ts'
import { Code } from '../util/codes.ts'
import { RarnError } from '../util/errors.ts'
import { INDEX_DIR_NAME } from './layout.ts'
import type { TypeExport } from './type-exports.ts'

/**
 * Generates the one-line ModuleScripts that connect requesters to packages.
 *
 * Every form indexes with bracketed strings rather than dots. An `_Index` entry name
 * contains `@` and `.`, and a package name may contain `-`, none of which are valid
 * after a dot in Luau. Bracketing everything keeps one shape instead of a rule about
 * when to switch.
 */

/**
 * The part of the header that identifies a file as Rarn's.
 *
 * Separate from the sentence around it because installing checks for it before
 * replacing a directory: rewording the advice must not turn every existing install
 * into a directory Rarn no longer recognises, which would refuse the next install
 * for everyone who has one.
 */
export const SHIM_MARKER = 'Generated by Rarn'

const HEADER = `-- ${SHIM_MARKER}. Do not edit; reinstalling overwrites this file.`

/** A direct dependency, reached from the realm directory root. */
export function rootShim(
  indexDirName: string,
  moduleName: string,
  types: readonly TypeExport[] = [],
): string {
  return line(`script.Parent.${INDEX_DIR_NAME}${index(indexDirName)}${index(moduleName)}`, types)
}

/**
 * A package's dependency, reached from beside that package's module folder.
 *
 * `script` is the shim, `script.Parent` is the requester's `_Index` entry, and
 * `script.Parent.Parent` is `_Index` itself — from which any other entry is reachable.
 */
export function siblingShim(
  indexDirName: string,
  moduleName: string,
  types: readonly TypeExport[] = [],
): string {
  return line(`script.Parent.Parent${index(indexDirName)}${index(moduleName)}`, types)
}

/**
 * A dependency in a different realm, reached by absolute DataModel path.
 *
 * Realms are separate top-level directories synced to different Roblox services, so
 * no `script.Parent` walk can cross between them — a relative path would have to go
 * up past the service boundary, which does not exist as a traversal. The absolute
 * path has to come from the manifest because only the project knows where it puts
 * each directory in the DataModel.
 */
export function crossRealmShim(
  placePath: string,
  indexDirName: string,
  moduleName: string,
  types: readonly TypeExport[] = [],
): string {
  return line(
    `${renderPlacePath(placePath)}.${INDEX_DIR_NAME}${index(indexDirName)}${index(moduleName)}`,
    types,
  )
}

/**
 * Turns a dotted DataModel path into Luau, bracketing what a dot cannot reach.
 *
 * `place` is written and derived as dot-separated names because that is how a person
 * says it, but an *instance* name has none of Luau's restrictions — Rojo is perfectly
 * happy with `"My Packages"`, and a project file saying so is where the derived path
 * comes from. Pasting that in verbatim produced
 * `require(game.ReplicatedStorage.My Packages._Index[...])`, which is not Luau at all:
 * the install succeeded, the tree was correct, and the file failed to parse in Studio.
 *
 * Only the segments that need it are bracketed, so the common path still reads as
 * `game.ReplicatedStorage.Packages` rather than as a row of quotes.
 */
function renderPlacePath(path: string): string {
  const [root, ...rest] = path.split('.')
  return rest.reduce(
    (built, segment) =>
      IDENTIFIER.test(segment) ? `${built}.${segment}` : `${built}${index(segment)}`,
    root ?? path,
  )
}

/** What Luau will accept after a dot. */
const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/

/**
 * The shim body: the require, and the type aliases it forwards.
 *
 * Luau carries a module's *value* through a link and none of its types, so without
 * the `export type` lines `require(Packages.React)` gives a `React` whose
 * `createElement` type-checks and whose `React.Node` is `Unknown type` — at every call
 * site, which makes `--!strict` signatures impossible to write against a typed
 * package. Half the registry exports types this way (300 of 584 packages in a warm
 * cache, 1943 aliases between them), and Wally has the same hole.
 *
 * A package with nothing to forward keeps the one-line shim it always had, which is
 * most of them and all of the diff people will see.
 */
function line(expression: string, types: readonly TypeExport[]): string {
  const require = `require(${expression})`
  if (types.length === 0) return `${HEADER}\nreturn ${require}\n`

  const binding = bindingName(types)
  return [
    HEADER,
    `local ${binding} = ${require}`,
    '',
    ...types.map(
      (type) =>
        `export type ${type.name}${generics(type.declared)} = ${binding}.${type.name}${generics(type.applied)}`,
    ),
    '',
    `return ${binding}`,
    '',
  ].join('\n')
}

function generics(parameters: string): string {
  return parameters === '' ? '' : `<${parameters}>`
}

/**
 * A local name for the required module that none of its own types will shadow.
 *
 * `export type Module` is a perfectly ordinary thing for a package to declare, and a
 * type alias sharing the binding's name would make every forwarded line refer to
 * itself.
 */
function bindingName(types: readonly TypeExport[]): string {
  const taken = new Set(types.map((type) => type.name))
  return ['Module', 'RarnModule', 'RarnLinkedModule'].find((name) => !taken.has(name)) ?? '_M'
}

/** `["evaera_promise@4.0.0"]` */
function index(name: string): string {
  return `[${JSON.stringify(name)}]`
}

/**
 * The `place` entry a cross-realm link needs, or a failure explaining what to add.
 *
 * Only `shared` and `server` are ever crossed *into*, and the signature says so rather
 * than a comment saying so. `dev` is the narrowest placement, so a dev-placed package
 * can only have dev-placed requesters — anything wider would have widened it. That is
 * also why `place` in the manifest has two fields and not three.
 *
 * It used to take a bare `Placement`, which meant a `dev` target fell through to
 * `serverPackages` and produced a shim pointing at the wrong service. Unreachable
 * today, but the kind of unreachable that a later change turns into a silently wrong
 * path rather than an error — `assertCrossable` makes it an error instead.
 */
export function requirePlacePath(
  place: PlaceInfo,
  target: Exclude<Placement, 'dev'>,
  requester: string,
): string {
  const declared = target === 'shared' ? place.sharedPackages : place.serverPackages
  if (declared !== undefined && declared !== '') return declared

  const field = target === 'shared' ? 'sharedPackages' : 'serverPackages'
  const example =
    target === 'shared' ? 'game.ReplicatedStorage.Packages' : 'game.ServerScriptService.Packages'

  throw new RarnError({
    code: Code.MissingPlacePath,
    what: `${requester} needs a '${target}' package, but rarn.json does not say where '${target}' packages live in the DataModel.`,
    where: 'rarn.json',
    detail: [
      '  Add a "place" entry, for example:',
      '',
      '    "place": {',
      `      "${field}": "${example}"`,
      '    }',
    ].join('\n'),
    how: `The two directories end up under different Roblox services, so the generated link has to name an absolute path. Set it to wherever you place the ${target} package directory.`,
  })
}

/**
 * Narrows a placement to one that can be crossed into.
 *
 * The invariant is real — placement resolves to the widest requester, so nothing
 * outside dev can point at a dev-placed package — but it is an invariant of the
 * resolver, enforced two layers away from here. This is where it gets checked, so
 * that breaking it produces a report rather than a shim naming the wrong service.
 */
export function assertCrossable(target: Placement, requester: string): Exclude<Placement, 'dev'> {
  if (target !== 'dev') return target

  throw new RarnError({
    code: Code.InternalError,
    what: `${requester} needs a cross-realm link into the 'dev' realm, which should not be reachable.`,
    how: 'This is a bug in Rarn. Please report it along with your rarn.json.',
  })
}
