import type { PlaceInfo } from '../manifest/types.ts'
import type { Placement } from '../resolver/types.ts'
import { Code } from '../util/codes.ts'
import { RarnError } from '../util/errors.ts'
import { INDEX_DIR_NAME } from './layout.ts'

/**
 * Generates the one-line ModuleScripts that connect requesters to packages.
 *
 * Every form indexes with bracketed strings rather than dots. An `_Index` entry name
 * contains `@` and `.`, and a package name may contain `-`, none of which are valid
 * after a dot in Luau. Bracketing everything keeps one shape instead of a rule about
 * when to switch.
 */

const HEADER = '-- Generated by Rarn. Do not edit; reinstalling overwrites this file.'

/** A direct dependency, reached from the realm directory root. */
export function rootShim(indexDirName: string, moduleName: string): string {
  return line(`script.Parent.${INDEX_DIR_NAME}${index(indexDirName)}${index(moduleName)}`)
}

/**
 * A package's dependency, reached from beside that package's module folder.
 *
 * `script` is the shim, `script.Parent` is the requester's `_Index` entry, and
 * `script.Parent.Parent` is `_Index` itself — from which any other entry is reachable.
 */
export function siblingShim(indexDirName: string, moduleName: string): string {
  return line(`script.Parent.Parent${index(indexDirName)}${index(moduleName)}`)
}

/**
 * A dependency in a different realm, reached by absolute DataModel path.
 *
 * Realms are separate top-level directories synced to different Roblox services, so
 * no `script.Parent` walk can cross between them — a relative path would have to go
 * up past the service boundary, which does not exist as a traversal. The absolute
 * path has to come from the manifest because only the project knows where it puts
 * each directory in the DataModel.
 */
export function crossRealmShim(
  placePath: string,
  indexDirName: string,
  moduleName: string,
): string {
  return line(`${placePath}.${INDEX_DIR_NAME}${index(indexDirName)}${index(moduleName)}`)
}

function line(expression: string): string {
  return `${HEADER}\nreturn require(${expression})\n`
}

/** `["evaera_promise@4.0.0"]` */
function index(name: string): string {
  return `[${JSON.stringify(name)}]`
}

/**
 * The `place` entry a cross-realm link needs, or a failure explaining what to add.
 *
 * Only `shared` and `server` are ever crossed *into*: `dev` is the narrowest
 * placement, so nothing outside dev can point at something placed there.
 */
export function requirePlacePath(place: PlaceInfo, target: Placement, requester: string): string {
  const declared = target === 'shared' ? place.sharedPackages : place.serverPackages
  if (declared !== undefined && declared !== '') return declared

  const field = target === 'shared' ? 'sharedPackages' : 'serverPackages'
  const example =
    target === 'shared' ? 'game.ReplicatedStorage.Packages' : 'game.ServerScriptService.Packages'

  throw new RarnError({
    code: Code.MissingPlacePath,
    what: `${requester} needs a '${target}' package, but rarn.json does not say where '${target}' packages live in the DataModel.`,
    where: 'rarn.json',
    detail: [
      '  Add a "place" entry, for example:',
      '',
      '    "place": {',
      `      "${field}": "${example}"`,
      '    }',
    ].join('\n'),
    how: `The two directories end up under different Roblox services, so the generated link has to name an absolute path. Set it to wherever you place the ${target} package directory.`,
  })
}
